sudo: required
services:
  - docker

before_install: 
 - docker build -t kilimanjaroo/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true kilimanjaroo/react-test npm test -- --coverage

after_success: 
  - docker build -t kilimanjaroo/multi-client ./client
  - docker build -t kilimanjaroo/multi-nginx ./nginx
  - docker build -t kilimanjaroo/multi-server ./server
  - docker build -t kilimanjaroo/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push kilimanjaroo/multi-client
  - docker push kilimanjaroo/multi-nginx
  - docker push kilimanjaroo/multi-server
  - docker push kilimanjaroo/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-716949460853'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY